apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/core/stack
  - ../../../components/metrics/stack
  - ../../../components/mcp/stack

resources:
  - mcp-podmonitor.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: streamshub-strimzi-mcp
    path: mcp-prometheus-patch.yaml
