apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - kubernetes-scrape-configs.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: streamshub-developer-quickstart
    includeSelectors: false
