apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/refs/tags/0.51.0/examples/kafka/kafka-single-node.yaml
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: streamshub-developer-quickstart
    includeSelectors: false

patches:
  - target:
      kind: Kafka
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-cluster
  - target:
      kind: KafkaNodePool
    patch: |-
      - op: replace
        path: /metadata/labels/strimzi.io~1cluster
        value: dev-cluster
  - target:
      kind: KafkaNodePool
    patch: |-
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaNodePool
      metadata:
        name: dual-role
      spec:
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
  - target:
      kind: Kafka
    patch: |-
      apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      metadata:
        name: dev-cluster
      spec:
        entityOperator:
          topicOperator:
            resources:
              requests:
                cpu: 250m
                memory: 384Mi
              limits:
                cpu: 250m
                memory: 384Mi
          userOperator:
            resources:
              requests:
                cpu: 250m
                memory: 384Mi
              limits:
                cpu: 250m
                memory: 384Mi
