apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/streamshub/streamshub-mcp//install/strimzi-mcp/base?ref=v0.2.0

labels:
  - pairs:
      app.kubernetes.io/part-of: streamshub-developer-quickstart
    includeSelectors: false

images:
  - name: quay.io/streamshub/strimzi-mcp
    newTag: "0.2.0"
