apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamshub-console

resources:
  - https://github.com/streamshub/console/releases/download/0.11.0/streamshub-console-operator.yaml
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: streamshub-developer-quickstart
    includeSelectors: false

patches:
  - target:
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: streamshub-console
  - target:
      kind: RoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: streamshub-console
  - target:
      kind: Deployment
      name: streamshub-console-operator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: streamshub-console-operator
      spec:
        template:
          spec:
            containers:
              - name: streamshub-console-operator
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 256Mi
